### ISSUE TITLE
leopard still in the link to the macosx packages

### ISSUE THREAD

**Issue by rnuske** [unDocUMeantIt/roxyPackage#1]
The link to the macosx package in file `[repository]/pckg/[package_name]/index.html` is still
`../../bin/macosx/leopard/contrib/3.2/package_0.2.1.tgz`
instead of
`../../bin/macosx/contrib/3.2/package_0.2.1.tgz`

The macosx packages are placed in `../../bin/macosx/contrib/3.2` leading to dead links.

The changelog entry for version 0.03-7 claims to have fixed

**Comment by unDocUMeantIt** [comment]
thanks for pointing this out. i confirm that the fix you mentioned only covered the actual repository, not the HTML page. this should be easy to fix though, i'm on it.

archive.packages() needs an update, too, but is urelated to this particular issue.

**Comment by unDocUMeantIt** [comment]
should be fixed with e694d72a18615be1fcfc58b2eaff944220306743 and c50ffb99ac2650222baf2fef8f3593402aa06ff3 in branch develop
