### ISSUE TITLE
The action "news2rss" causes XiMpLe warnings

### ISSUE THREAD

**Issue by rnuske** [unDocUMeantIt/roxyPackage#12]
This is probably not the perfect place for this issue, since it seems to be rather an XiMpLe issue. I post it here because my only contact with XiMpLe is through roxyPackage and XiMpLe seems not to boast a public repository.

30 identical warnings are cause by 
```
library(roxyPackage)
roxy.package(pck.source.dir="~/localPackage",
             R.libs='/home/rnuske/R/x86_64-pc-linux-gnu-library/3.3',
             repo.root="~/myTestPkgs",
             URL="https://somedomain.de/myTestPkgs",
             pck.description=NULL,
             actions=c("news2rss"))
```

One of the warnings:
```
> warnings()[1]
Warnmeldung:
In `[<-`(`*tmp*`, nxt.child, value = <S4 object of class structure("XiMpLe.node", package = "XiMpLe")>) :
  implicit list embedding of S4 objects is deprecated
```

**Comment by unDocUMeantIt** [comment]
> XiMpLe seems not to boast a public repository.

actually, it [does](https://github.com/rkward-community/XiMpLe), and i have even better news: the problem was already fixed in the develop branch a while ago, but i didn't release it yet. i've just uploaded it to CRAN, if all goes well the problem should be gone soon.

**Comment by unDocUMeantIt** [comment]
(`XiMpLe` 0.10-1 is on CRAN already!)

**Comment by rnuske** [comment]
cool. checked it, no warnings no more :-)

I looked at XiMpLe's `DESCRIPTION` and didn't find a link to a repository and checked your github repositories to no avail. I thought, I also thoroughly searched https://reaktanz.de/?c=hacking&s=XiMpLe. But obviously I didn't.
Maybe I would be a good idea to put the link to the github repo in the `DESCRIPTION`.
