### ISSUE TITLE
ORCID symbol in authors list

### ISSUE THREAD

**Issue by rnuske** [unDocUMeantIt/roxyPackage#14]
I wanted nice linked ORCID icons in the author list  instead of `(<https://orcid.org/....>)`

I tried to do it myself and got lost in the XML Nodes.

My idea was to put orcid.svg in inst/images, copy it over to the repository like the feed-icon and 
replace all `(<https://orcid.org/....>)` of pckg.participants in roxy.html.R with `<a href="https://orcid.org/..."><img alt="ORCID iD" src="../orcid.svg" style="width:16px; height:16px; margin-left:4px; margin-right:4px; vertical-align:middle" /></a>` (copied from CRAN).

I thought it would be a good idea to add a parameter `orcid` to `rx.clean()` and do something like
```
if(isTRUE(orcid)){
    # replace ORCID comments with link and ORCID image
    # orcid pattern from wikidata
    while(grepl("\\(<https://orcid.org/0000-000(1-[5-9]|2-[0-9]|3-[0-4])\\d{3}-\\d{3}[\\dX]>\\)", txt, perl=TRUE)){
      txt <- sub("\\(<(https://orcid.org/0000-000(1-[5-9]|2-[0-9]|3-[0-4])\\d{3}-\\d{3}[\\dX])>\\)",
                 '<a href="\\1"><img alt="ORCID iD" src="../orcid.svg" style="width:16px; height:16px; margin-left:4px; margin-right:4px; vertical-align:middle" />', txt, perl=TRUE)
    }
  } else {}
```
This leads to serious quoting issues (cf. a4893fcff8c77be3f931dfc00b00a14861a2ea50)

Maybe one could split the string,  replace the ORCID comments with XMLNode('a', XMLNode('img', ...)) and wrap everythin in an XMLNode('p' or 'span'...

A helping hand is much appreciated.

**Comment by unDocUMeantIt** [comment]
could you hint me to an example `DESCRIPTION` and the desired output so i'd have something to toy around with?

**Comment by rnuske** [comment]
Most Packages by Yihui Xie, e.g. [xaringan DESCRIPTION](https://github.com/yihui/xaringan/blob/master/DESCRIPTION) and how it looks on  [CRAN](https://CRAN.R-project.org/package=xaringan).

and its recommended by ROpenSci, e.g. [RefManageR DESCRIPTION](https://github.com/ropensci/RefManageR/blob/master/DESCRIPTION) and how it looks on [CRAN](https://CRAN.R-project.org/package=RefManageR).

**Comment by unDocUMeantIt** [comment]
i see. from a first glance i'd think that it should be a much better and easier approach to not replace any already rendered HTML tags but to examine the `comment` arguments of given `person()` calls and handle entries called `ORCID` accordingly.

i haven't looked it up in the code yet, but there's one or more internal functions dealing with `person()` already, which should be a good place to start.

**Comment by rnuske** [comment]
I did not try to hack the HTML. The `(<https://...>)` string is the result of the `person()` function

```
> c(
   person("Robert", "Nuske", role=c("aut", "cre"), email="someone@somewhere.org",
     comment=c(ORCID="0000-0002-9674-3072")),
   person("Dirk", "Eddelbuettel", role="aut")
  )
#> [1] "Robert Nuske <someone@somewhere.org> [aut, cre] (<https://orcid.org/0000-0002-9674-3072>)"
#> [2] "Dirk Eddelbuettel [aut]"            
```

**Comment by unDocUMeantIt** [comment]
i've started a new branch `orcid` as a playground. it's not quite working as intended, adding escaped hyperlink code readable to the HTML page and destroying the layout, but it looks like it's pointing to the right direction

**Comment by unDocUMeantIt** [comment]
i'm having a hard time figuring out how person objects can be manipulated without making it unusable. accessing values like `obj$comment` works, but `obj$comment <- "new value"` seems to invalidate the object, turning it into an ordinary list for `format()`. i'll try to combine multiple calls to `format()` and paste them together in a single string.

**Comment by unDocUMeantIt** [comment]
there's now working code in the `orcid` branch, please check it out!

i'm not sure about including the SVG file in the package, i haven't read up on licensing terms (i understand the green logo is only to be displayed for authenticated IDs)

**Comment by rnuske** [comment]
looks good for one orcid in participants. If there is more than one, only the last gets turned into a link. That's why I tried `while(grepl()) gsub()` to catch all orcids

I do not understand why the orcid needs to be handled in roxyPackage-internal.R. Untreated a participant with orcid leaves get.authors() as `Robert Nuske [aut, cre] (<https://orcid.org/0000-0001-9773-2061>)` (created using branch develop). If the links need to be transformed in roxy-html.R anyway, everything could be done there.

**Comment by rnuske** [comment]
I am not sure i understand what ORCID wants to achieve with its license terms. more specific 'what is meant by authenticate'? I guess from the context, hat the green logo should not be displayed along not valid ORCIDs. From personal experience with journals and CRAN: I was never asked to enter my ORCID password. They might have checked that the ORCID resolves to a profile matching my name.

one could try to check that in code/algorithmic maybe using ideas from `rorcid` or ask the roxyPackage user to validate all ORCIDs via a parameter such as `orcids.valid=TRUE`.

**Comment by unDocUMeantIt** [comment]
> I do not understand why the orcid needs to be handled in roxyPackage-internal.R. Untreated a participant with orcid leaves get.authors() as `Robert Nuske [aut, cre] (<https://orcid.org/0000-0001-9773-2061>)` (created using branch develop). If the links need to be transformed in roxy-html.R anyway, everything could be done there.

ORCID is just one possible comment a person could have. the regular expression to successfully extract one particular URL and not harm the rest of a comment would be rather complex. i think it's easierand less prone to errors to pre-format the string via `get.authors()` with the `person` object directly available, but do the transformation into HTML by `roxy.html()`.

i'll look into the issue of missing links.

**Comment by unDocUMeantIt** [comment]
should work now for multiple persons

**Comment by rnuske** [comment]
It does, thanks!

**Comment by rnuske** [comment]
Would you be willing to add the orcid icon and copy it to the HTML repo or should I handle that in a local fork?

**Comment by unDocUMeantIt** [comment]
> Would you be willing to add the orcid icon and copy it to the HTML repo or should I handle that in a local fork?

i'm currently thinking of a function that would download the icon directly from orcid.org, to be called manually (`roxy.package()` would check if the icon is missing and print a message). at least as a temporary workaround to solve the authentication problem.

**Comment by rnuske** [comment]
As I understood the orcid icon license, it is allowed to pass on the icon but it should not be displayed next to invalid orcid ids. Thus, it should be no problem to include the icon in the roxypackage. Users of roxypackage should be made aware that they have to ensure, they use the icon only with valid orcids (I've got the feeling CRAN checks orcid validity only by the regex an orid has to pass).

Maybe a `roxy.package(actions='validORCID')` would be a good way to force the user to think about usage of the icon (Like forcing a house buyer to sign the  contract with the notary, so that he is aware of what he is doing). If this action is selected the orcid icon should be copied over to the repo and the links should use the icon. Without the action the links should look different (the icon could already be in the repo because of another package offered in the same repo).

**Comment by unDocUMeantIt** [comment]
after thinking about this a while: generally, i think we don't need to replicate functionality from the `rorcid` package, which i understand could be used to authenticate IDs. so for me it's entirely up to the maintainer of a repository to take care of this, it's a bit out of scope of `roxyPackage`.

the current `develop` version now informs you if the icon is missing and explains how you can fix this by simply calling `orcid_icon_fetcher("<path to repo>")`. since this is only to be done once, this should be comfortable enough, don't you agree?

**Comment by rnuske** [comment]
It's really very sad that you don't want to include support for managing the ORCID icon at all. I hoped for a little helper for the repo admin since `roxypackage` seemed to bundle all functionality needed for creating and updating a local CRAN like repository.

I looked at `rorcid` before I did my first tests with linking orcids. I didn't find simple functionality to check ORCIDs. One needs to authenticate oneself before one can ask the ORCID-API for e.g. names associated with an ID. Nevertheless, this could be suggested to the repo manager/roxypackage user for checking the ORCIDs. 

My heartfelt wish and suggestion would be, that if the manager ensures she/he has checked the ORCIDs and they are OK, he/she can ask roxypackage to manage the icon.

**Comment by unDocUMeantIt** [comment]
hm, what exactly do you mean by "managing the ORCID icon"? as i understand it, it only needs to be copied to the repository once, which can now be done easily by simply running the new `roxyPackage` function `orcid_icon_fetcher()` -- have you tried it? also, the code already has a regex check for valid ID format and only transorms links if they pass the test. i really don't want to go any further with checks than this, because the public ORCID API can only be used with registered applications, so i don't see any advantage over the existing `rorcid` package.

so the only hassle is that `orcid_icon_fetcher()` is not being called automatically (but `roxyPackage` will tell you when you should do so, including code for copy&paste use). on the other hand, you don't need any new actions, the existing `html` action does it all already.

**Comment by rnuske** [comment]
While experimenting with some repositories I've done this a few times now, and `orcid_icon_fetcher()` seems practical enough.
