### ISSUE TITLE
Add 'Materials:' to package HTML-page and list README

### ISSUE THREAD

**Issue by rnuske** [unDocUMeantIt/roxyPackage#15]
CRAN lists html versions of README and NEWS (and other stuff such as ChangeLog in plain text) in the field `Materials`.

README and NEWS are generated from Markdown files. ChangLog is probably untreated.

Thus, I would suggest to handle README.md and NEWS.md in the same way as the vignettes: render to HTML and add to package HTML-page if available and shift the ChangLog file from `News/Changelog` to `Materials`.

**Comment by unDocUMeantIt** [comment]
a good idea.

linking those files differently shouldn't be much of an issue. but do you know how CRAN does the rendering to HTML of REAMDE.md and NEWS.md? i don't think `R CMD build` does it (but i haven't tested that).

**Comment by rnuske** [comment]
nope I have no idea how CRAN does it. I guess using pandoc, found a hint in [r-source check.R](https://github.com/wch/r-source/blob/33f098c26fa578fb5cc20be133e0e3d4e5faa766/src/library/tools/R/check.R#L1267)

**Comment by rnuske** [comment]
CRAN searches at toplevel and in inst for README.md and NEWS.md. It still seems to accept inst/News.Rd (see Rcpp [Github](https://github.com/RcppCore/Rcpp), [CRAN](https://CRAN.R-project.org/package=Rcpp)). If the files are plain text they get linked as plain text (e.g. [git2r NEWS](https://github.com/ropensci/git2r/NEWS), [CRAN](https://CRAN.R-project.org/package=git2r) and [Rcpp ChangeLog](https://github.com/RcppCore/Rcpp/blob/master/ChangeLog))

**Comment by unDocUMeantIt** [comment]
looks like adding the `rmarkdown` package to the dependencies would be neccessary to accomplish this. i must say i'm ususally very hesitant when it comes to new dependencies ;)

**Comment by rnuske** [comment]
I understand the reluctance to accept new dependencies. But I think one would not need `rmarkdown` "only" the `pandoc` executable, CRAN does a [system call](https://github.com/wch/r-source/blob/617edf583e602235e1913835acfe5d6db8c921ae/src/library/tools/R/utils.R#L1799).

**Comment by unDocUMeantIt** [comment]
ah, that means it can actually be called:

```r
tools:::.pandoc_md_for_CRAN("README.md", "README.html")
```

**Comment by unDocUMeantIt** [comment]
in the `develop` branch, the ChangeLog or NEWS are now listed under "Materials". the markdown files should also already be compiled to HTML if `pandoc` was found. what's missing now is their inclusion as "Materials". maybe something for the train ride ahead.

**Comment by rnuske** [comment]
Looks great @unDocUMeantIt !

README and NEWS were rendered to html and README  is already perfectly listed and linked under Materials.

**Comment by rnuske** [comment]
#16 adds NEWS to Materials as well

**Comment by rnuske** [comment]
Thanks!
