### ISSUE TITLE
revise advise on 'Build for several R versions'

### ISSUE THREAD

**Issue by rnuske** [unDocUMeantIt/roxyPackage#7]
Since now packages for all R versions are linked in the HTML index, the newest version doesn't have to be on the last position. It might rather be advantageous to have the newest R version on first position since the docs are only build in the first run. A problem for example is that Rd2pdf in R-3.0.3 has problems with links (\href{}) in help pages and thus builds no pdf.

**Comment by unDocUMeantIt** [comment]
linking to all available R versions is a rather young feature. i'm not sure i understand you correctly -- do you suggest having just the links in a different order or a change of the build workflow as a whole?

**Comment by rnuske** [comment]
Writing the issue, it seemed clear. But reading it again, I have to admit its hard to understand  :-(

I try it again:
I want to suggest to change one paragraph of the help page of `roxy.package()`. The help page contains the paragraph 'Build for several R versions' with tips for building a package for more than one R version.  At the moment the paragraph suggests to order the R versions from oldest to newest because the last is linked in the HTML index. This is not true anymore. 
I found the reverse order advisable because I had trouble with old R versions not beeing able to build the reference manual from the help pages (Rd2pdf in R-3.0.3 was not able to handle non trivial links to websites).

I hope I expressed myself more clearly this time.

**Comment by unDocUMeantIt** [comment]
ok, now i get it ;-) i've just commited some changes, can you check it out and give me feedback if that's what you had in mind?

i had to move the debian packaging from last to first round of builds, needs some testing to make sure this didn't break anything (it shouldn't though).

**Comment by rnuske** [comment]
Yep, that's  kind of what I had in mind. 

I would only suggest to add a hint, that older R version might not have all capabilities needed for successfully doing that task.

**Comment by unDocUMeantIt** [comment]
the docs now recommend to always put the most recent R version first. this should be the very information one needs, given that it should be rather obvious that older software might not be able to do all the things new versions are capable of.
