### ISSUE TITLE
CRAN like author field on package html page

### ISSUE THREAD

**Issue by rnuske** [unDocUMeantIt/roxyPackage#9]
Gaining more and more contributors to packages published with the help of roxyPackage their legitimate demand to be visible in the DESCRIPTION and on the package html page increases.

The Author lines on CRAN's html pages look something like (with very rare exceptions):
Edzer Pebesma [aut, cre], Roger Bivand [ctb], Ian Cook [ctb], Tim Keitt [ctb], Michael Sumner [ctb], Robin Lovelace [ctb], Hadley Wickham [ctb], Jeroen Ooms [ctb], Etienne Racine [ctb]

Hadley Wickham [aut, cre], Romain Francois [aut], RStudio [cph]

Paolo Sonego [aut, cph, cre], Mikko Korpela [aut]

If I understood the process flow correctly, I guess get.authors() needs the ability to return such a line and roxy.html() should ask for this new ability instead of just the Author.

Am I right?
Would you accept a corresponding PR?

**Comment by unDocUMeantIt** [comment]
i didn't check this in detail, but that could be a solution. CRAN uses the `Authors@R` field for this (it also generates the `Author` field in `DESCRIPTION` from this). generally, this shouldn't be too much code, something like following should do the trick:

```
eval(parse(text=package.description[["AutorsR"]]))
```

probably with a call to `format()` to strip a-mail addresses. feel free to toy around with this!

**Comment by rnuske** [comment]
will do

**Comment by rnuske** [comment]
Your hint made it really easy. Thanks a lot. Would have taken me way longer without it.

**Comment by unDocUMeantIt** [comment]
thanks, i've merged the pull request. i've also taken the liberty of adding you to the list of contributors to the package, hope you're fine with that ;-)

i'll close this issue with a hint to examine whether the author info in `CITATION` files must be updated as well.

**Comment by rnuske** [comment]
Thanks @unDocUMeantIt , that's truly an honor.
I love how easy it is to create a local CRAN-like repository with roxyPackage.
